@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjFlYjI0YzNlOTQ4ZjcwMzQwZDAyZSIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlhdCI6MTc4NDk1MTIwOSwiZXhwIjoxNzg1MDM3NjA5fQ.eZ-9Z3etGLXWSHvx1WhOCzC9PqUi23Xi3lspS33zqOM
POST http://localhost:5000/api/clients
Content-Type: application/json

{
  "companyName": "ABC Technologies",
  "companyCode": "ABC001",
  "industry": "IT",
  "subscriptionPlan": "Premium",
  "contactEmail": "info@abc.com",
  "phoneNumber": "9876543210",
  "status": 1
}


### Get All Clients (Protected)

GET http://localhost:5000/api/clients
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjFlYjI0YzNlOTQ4ZjcwMzQwZDAyZSIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlhdCI6MTc4NDg3NTY3NywiZXhwIjoxNzg0OTYyMDc3fQ.GmRlHCml856ixLfPO1meMFKqKMZgj52qBf2f-HyC_XA
### Get Client By ID
GET http://localhost:5000/api/clients/6a60d0369889c7dc322bfd74

### Update Client
PUT http://localhost:5000/api/clients/6a60d0369889c7dc322bfd74
Content-Type: application/json

{
  "companyName": "ABC Technologies Pvt Ltd",
  "companyCode": "ABC001",
  "industry": "Software",
  "subscriptionPlan": "Enterprise",
  "contactEmail": "support@abc.com",
  "phoneNumber": "9123456789",
  "status": 1
}
### Delete Client
DELETE http://localhost:5000/api/clients/6a61afca6bcb4cd4564db13e


### Create Client (New Test Data)
POST http://localhost:5000/api/clients
Content-Type: application/json

{
  "companyName": "CDE Technologies",
  "companyCode": "CDE001",
  "industry": "IT",
  "subscriptionPlan": "Premium",
  "contactEmail": "info@xyz.com",
  "phoneNumber": "9876543120",
  "status": 1
}

### Get All Clients
GET http://localhost:5000/api/clients

### Search by Company Name
GET http://localhost:5000/api/clients?search=ABC

### Search by Company Code
GET http://localhost:5000/api/clients?search=ABC001

### Search by Industry
GET http://localhost:5000/api/clients?search=IT

### Search by Subscription Plan
GET http://localhost:5000/api/clients?search=Premium

### Search by Email
GET http://localhost:5000/api/clients?search=info@abc.com

### Page 1
GET http://localhost:5000/api/clients?page=1&limit=1

### Page 2
GET http://localhost:5000/api/clients?page=2&limit=1

### Page 3
GET http://localhost:5000/api/clients?page=3&limit=1

### Search + Pagination
GET http://localhost:5000/api/clients?search=IT&page=1&limit=1

### Missing Company Name
POST http://localhost:5000/api/clients
Content-Type: application/json

{
  "companyCode": "AAA001",
  "industry": "IT",
  "subscriptionPlan": "Premium",
  "contactEmail": "abc@test.com",
  "phoneNumber": "9876543210"
}

### Invalid Email
POST http://localhost:5000/api/clients
Content-Type: application/json

{
  "companyName": "ABC",
  "companyCode": "AAA002",
  "industry": "IT",
  "subscriptionPlan": "Premium",
  "contactEmail": "abc",
  "phoneNumber": "9876543210"
}

### Invalid Phone
POST http://localhost:5000/api/clients
Content-Type: application/json

{
  "companyName": "ABC",
  "companyCode": "AAA003",
  "industry": "IT",
  "subscriptionPlan": "Premium",
  "contactEmail": "abc@test.com",
  "phoneNumber": "12345"
}

### Invalid Status
POST http://localhost:5000/api/clients
Content-Type: application/json

{
  "companyName": "ABC",
  "companyCode": "AAA004",
  "industry": "IT",
  "subscriptionPlan": "Premium",
  "contactEmail": "abc@test.com",
  "phoneNumber": "9876543210",
  "status": 5
}

### Duplicate Company Code
POST http://localhost:5000/api/clients
Content-Type: application/json

{
  "companyName": "Another Company",
  "companyCode": "ABC001",
  "industry": "IT",
  "subscriptionPlan": "Premium",
  "contactEmail": "another@test.com",
  "phoneNumber": "9999999999"
}

### Super Admin Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "superadmin@gmail.com",
  "password": "Admin@123"
}

### Invalid Super Admin Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "superadmin@gmail.com",
  "password": "WrongPassword"
}

### Create Client (Protected)

POST http://localhost:5000/api/clients
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
Content-Type: application/json

{
  "companyName": "XYZ Technologies",
  "companyCode": "XYZ001",
  "industry": "IT",
  "subscriptionPlan": "Premium",
  "contactEmail": "info@xyz.com",
  "phoneNumber": "9876543211",
  "status": 1
}

### Super Admin Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "superadmin@gmail.com",
  "password": "Admin@123"
}

### Get All Clients (Protected)
GET http://localhost:5000/api/clients
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjFlYjI0YzNlOTQ4ZjcwMzQwZDAyZSIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlhdCI6MTc4NDg3NjcyMywiZXhwIjoxNzg0OTYzMTIzfQ.nwVxQoTpMvOZMhuB4K3eX9h6Uo-h2QyIfMEXqQLECnw

### Get All Clients (Without Token)
GET http://localhost:5000/api/clients

### Create Company Admin

POST http://localhost:5000/api/company-admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjFlYjI0YzNlOTQ4ZjcwMzQwZDAyZSIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlhdCI6MTc4NDk3NzYzOCwiZXhwIjoxNzg1MDY0MDM4fQ.-c4i4re8aM_wW8Pw2HR0WyzdXy7JlEal-QyNWT4Qk00
Content-Type: application/json

{
  "clientId": "6a61aee16bcb4cd4564db13a",
  "firstName": "justin",
  "lastName": "beber",
  "email": "g81332838@gmail.com",
  "phoneNumber": "9876544210"
}

### Company Admin Login

POST http://localhost:5000/api/company-admin/login
Content-Type: application/json

{
  "email": "john@company.com",
  "password": "Admin@123"
}

### Super Admin Login

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "superadmin@gmail.com",
  "password": "Admin@123"
}

### Get All Company Admins

GET http://localhost:5000/api/company-admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjFlYjI0YzNlOTQ4ZjcwMzQwZDAyZSIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlhdCI6MTc4NDk1MjQ2MCwiZXhwIjoxNzg1MDM4ODYwfQ.FeTdiuy4WmRGUn47gVoIoxA-V66P-_klYDn91iQDOhM



### Search Company Admin by First Name

GET http://localhost:5000/api/company-admin?search=John
Authorization: Bearer {{token}}

### Search Company Admin by Last Name

GET http://localhost:5000/api/company-admin?search=Doe
Authorization: Bearer {{token}}

### Search Company Admin by Email

GET http://localhost:5000/api/company-admin?search=john@company.com
Authorization: Bearer {{token}}

### Search Company Admin by Phone Number

GET http://localhost:5000/api/company-admin?search=9876543210
Authorization: Bearer {{token}}

### Company Admin Pagination - Page 1

GET http://localhost:5000/api/company-admin?page=1&limit=2
Authorization: Bearer {{token}}

### Company Admin Pagination - Page 2

GET http://localhost:5000/api/company-admin?page=2&limit=2
Authorization: Bearer {{token}}

### Search + Pagination

GET http://localhost:5000/api/company-admin?search=John&page=1&limit=2
Authorization: Bearer {{token}}

### Unauthorized Request

GET http://localhost:5000/api/company-admin

### Update Company Admin

PUT http://localhost:5000/api/company-admin/6a631315d719de44424c8a7d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjFlYjI0YzNlOTQ4ZjcwMzQwZDAyZSIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlhdCI6MTc4NDk1ODYzMiwiZXhwIjoxNzg1MDQ1MDMyfQ.qjmlq8Bf-u-5lAGlTq4b2rS8CXn--inWwnv22E8gLOM
Content-Type: application/json

{
  "firstName": "Johnny",
  "lastName": "Doe",
  "phoneNumber": "9999999999",
  "status": 1
}

### Get Company Admin By ID

GET http://localhost:5000/api/company-admin/6a631315d719de44424c8a7d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjFlYjI0YzNlOTQ4ZjcwMzQwZDAyZSIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlhdCI6MTc4NDk1ODYzMiwiZXhwIjoxNzg1MDQ1MDMyfQ.qjmlq8Bf-u-5lAGlTq4b2rS8CXn--inWwnv22E8gLOM

### Delete Company Admin

DELETE http://localhost:5000/api/company-admin/6a631315d719de44424c8a7d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjFlYjI0YzNlOTQ4ZjcwMzQwZDAyZSIsInJvbGUiOiJTVVBFUl9BRE1JTiIsImlhdCI6MTc4NDk1ODYzMiwiZXhwIjoxNzg1MDQ1MDMyfQ.qjmlq8Bf-u-5lAGlTq4b2rS8CXn--inWwnv22E8gLOM

### ==========================================
### Create Project Manager
### ==========================================

POST http://localhost:5000/api/project-manager
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjMxMzE1ZDcxOWRlNDQ0MjRjOGE3ZCIsInJvbGUiOiJDT01QQU5ZX0FETUlOIiwiaWF0IjoxNzg0OTg4MjE0LCJleHAiOjE3ODUwNzQ2MTR9.oEMMiNOmudetmywoXUn93anthRmW6FwX2D1qBU6wu-Y
Content-Type: application/json

{
  "companyAdminId": "6a631315d719de44424c8a7d",
  "firstName": "David",
  "lastName": "Miller",
  "email": "david.manager10@example.com",
  "phoneNumber": "9876543211"
}

### Project Manager Login

POST http://localhost:5000/api/project-manager/login
Content-Type: application/json

{
  "email": "david.manager10@example.com",
  "password": "Manager@123"
}

### Get All Project Managers

GET http://localhost:5000/api/project-manager?page=1&search=
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjMxMzE1ZDcxOWRlNDQ0MjRjOGE3ZCIsInJvbGUiOiJDT01QQU5ZX0FETUlOIiwiaWF0IjoxNzg0OTk5NDQxLCJleHAiOjE3ODUwODU4NDF9.tHHIjl3K-SO7JcEdjFAQiuvPIpw86fmPmIqqNNOeEgM

### Get Project Manager By ID

GET http://localhost:5000/api/project-manager/6a64cb6d38871a30dbcef9f5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjMxMzE1ZDcxOWRlNDQ0MjRjOGE3ZCIsInJvbGUiOiJDT01QQU5ZX0FETUlOIiwiaWF0IjoxNzg1MDAwMTA3LCJleHAiOjE3ODUwODY1MDd9.XqnJUFrHchWjiV8NF-b8vkrHcQZKl-sUXdlJbUCPwQU

### Update Project Manager

PUT http://localhost:5000/api/project-manager/6a64cb6d38871a30dbcef9f5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjMxMzE1ZDcxOWRlNDQ0MjRjOGE3ZCIsInJvbGUiOiJDT01QQU5ZX0FETUlOIiwiaWF0IjoxNzg1MDMyMjEyLCJleHAiOjE3ODUxMTg2MTJ9.OhnnvW6PFQOEWSQhwzDAE9uhvmAEitjsCtcJVCNKRbs
Content-Type: application/json

{
  "firstName": "David Updated",
  "lastName": "Miller",
  "email": "david.manager10@example.com",
  "phoneNumber": "9999999999",
  "status": 1
}

### Delete Project Manager

DELETE http://localhost:5000/api/project-manager/6a64cb6d38871a30dbcef9f5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjMxMzE1ZDcxOWRlNDQ0MjRjOGE3ZCIsInJvbGUiOiJDT01QQU5ZX0FETUlOIiwiaWF0IjoxNzg1MDMyMjEyLCJleHAiOjE3ODUxMTg2MTJ9.OhnnvW6PFQOEWSQhwzDAE9uhvmAEitjsCtcJVCNKRbs

### Create Team Member

POST http://localhost:5000/api/team-member
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjMxMzE1ZDcxOWRlNDQ0MjRjOGE3ZCIsInJvbGUiOiJDT01QQU5ZX0FETUlOIiwiaWF0IjoxNzg1MDMyMjEyLCJleHAiOjE3ODUxMTg2MTJ9.OhnnvW6PFQOEWSQhwzDAE9uhvmAEitjsCtcJVCNKRbs
Content-Type: application/json

{
  "companyAdminId": "6a631315d719de44424c8a7d",
  "projectManagerId": "6a64c2b42dc6b33ffa512e62",
  "firstName": "Ram",
  "lastName": "Sharma",
  "email": "ram.team@example.com",
  "phoneNumber": "9876643210"
}
### Get Team Members

GET http://localhost:5000/api/team-member?page=1&limit=5&search=
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjMxMzE1ZDcxOWRlNDQ0MjRjOGE3ZCIsInJvbGUiOiJDT01QQU5ZX0FETUlOIiwiaWF0IjoxNzg1MDMyMjEyLCJleHAiOjE3ODUxMTg2MTJ9.OhnnvW6PFQOEWSQhwzDAE9uhvmAEitjsCtcJVCNKRbs

### Get Team Member By ID

GET http://localhost:5000/api/team-member/6a658bc1a9edcfde34d4fa7e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjMxMzE1ZDcxOWRlNDQ0MjRjOGE3ZCIsInJvbGUiOiJDT01QQU5ZX0FETUlOIiwiaWF0IjoxNzg1MDMyMjEyLCJleHAiOjE3ODUxMTg2MTJ9.OhnnvW6PFQOEWSQhwzDAE9uhvmAEitjsCtcJVCNKRbs

### Update Team Member

PUT http://localhost:5000/api/team-member/6a658bc1a9edcfde34d4fa7e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjMxMzE1ZDcxOWRlNDQ0MjRjOGE3ZCIsInJvbGUiOiJDT01QQU5ZX0FETUlOIiwiaWF0IjoxNzg1MDQwOTEwLCJleHAiOjE3ODUxMjczMTB9.OVKK4Gl18sI-Ce4E_dPwEIdrEF9dxk7jSNK5ghJeIgo
Content-Type: application/json

{
  "projectManagerId": "6a64cb6d38871a30dbcef9f5",
  "firstName": "Amit",
  "lastName": "Kumar",
  "email": "amit.team@example.com",
  "phoneNumber": "9999999999",
  "status": 1
}
### Delete Team Member

DELETE http://localhost:5000/api/team-member/6a658bc1a9edcfde34d4fa7e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjMxMzE1ZDcxOWRlNDQ0MjRjOGE3ZCIsInJvbGUiOiJDT01QQU5ZX0FETUlOIiwiaWF0IjoxNzg1MDQwOTEwLCJleHAiOjE3ODUxMjczMTB9.OVKK4Gl18sI-Ce4E_dPwEIdrEF9dxk7jSNK5ghJeIgo

### Team Member Login

POST http://localhost:5000/api/team-member/login
Content-Type: application/json

{
  "email": "ram.team@example.com",
  "password": "Member@123"
}
### Toggle Team Member Status

PATCH http://localhost:5000/api/team-member/6a658bc1a9edcfde34d4fa7e/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjMxMzE1ZDcxOWRlNDQ0MjRjOGE3ZCIsInJvbGUiOiJDT01QQU5ZX0FETUlOIiwiaWF0IjoxNzg1MDYzMjU2LCJleHAiOjE3ODUxNDk2NTZ9.Nr8ySbIou9VPdAPdGbWdNfNKmEoZINIu7C0Ql5gl_U0

### Fix Existing Team Members

PATCH http://localhost:5000/api/team-member/fix-clientids
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjMxMzE1ZDcxOWRlNDQ0MjRjOGE3ZCIsInJvbGUiOiJDT01QQU5ZX0FETUlOIiwiaWF0IjoxNzg1MDYzNjIwLCJleHAiOjE3ODUxNTAwMjB9.82teTbud9DbGid75V2RlPUcKdbfOa5RDDrCV6rbama0

### ==========================================
### Unified Login (All Users)
### ==========================================

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "superadmin@gmail.com",
  "password": "Admin@123"
}