POST http://localhost:5000/api/clients
Content-Type: application/json

{
  "companyName": "ABC Technologies",
  "companyCode": "ABC001",
  "industry": "IT",
  "subscriptionPlan": "Premium",
  "contactEmail": "info@abc.com",
  "phoneNumber": "9876543210",
  "status": 1
}

### Get All Clients
GET http://localhost:5000/api/clients

### Get Client By ID
GET http://localhost:5000/api/clients/6a60d0369889c7dc322bfd74